[package]
name = "svy_rs"
version = "0.3.0"
edition = "2021"

[lib]
name = "_internal"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26", features = ["abi3-py311", "extension-module", "generate-import-lib"] }
pyo3-polars = { version = "0.25", features = ["derive"] }
polars = { version = "0.52", default-features = false, features = ["dtype-categorical"] }
faer = "0.19"
ahash = "0.8"
numpy = "0.26"
ndarray = { version = "0.16", features = ["rayon"] }
rayon = "1.10"
thiserror = "2.0"
approx = "0.5.1"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
