[project]
name = "svy_rs"
version = "0.3.0"
description = "Efficient survey statistics for Polars"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "polars[pyarrow]>=1.8.2",
]

[project.optional-dependencies]
dev = [
    "black>=24.10.0",
    "maturin>=1.7.7",
    "mypy>=1.13.0",
    "pytest>=8.3.4",
    "ruff>=0.8.1",
]

[tool.maturin]
module-name = "svy_rs._internal"
python-source = "."
features = ["pyo3/extension-module"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
