[project]
name = "svy_rs"
version = "0.3.0"
description = "Internal Rust extension for the svy package. Do not depend on this directly."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "../../LICENSE" }
authors = [{ name = "Samplics LLC", email = "msdiallo@samplics.org" }]
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Development Status :: 4 - Beta",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering",
]
dependencies = [
    "polars[pyarrow]>=1.8.2",
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "svy_rs._internal"
python-source = "."
features = ["pyo3/extension-module"]
