[package]
name = "polars_svy"
version = "0.2.0"
edition = "2021"

[lib]
name = "_internal"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26", features = ["abi3-py38", "extension-module", "generate-import-lib"] }
pyo3-polars = { version = "0.25", features = ["derive"] }
polars = { version = "0.52", default-features = false, features = ["dtype-categorical"] }

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
